---
- name: Get kind executable file
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
    owner: root
    group: root
    mode: 0775
    dest: /usr/local/bin/kind

- name: Create a single-node cluster 
  ansible.builtin.command:
    cmd: /usr/local/bin/kind create cluster
  when: multi_node == false
    
- name: Create a three-node cluster
  vars:
    config_file_path: /root/cluster.yaml
  block:
    - name: Create a manifest in .yaml format
      ansible.builtin.template:
        src: cluster.j2
        dest: "{{ config_file_path }}"
        mode: 0644
        owner: root
        group: root
      when: multi_node

    - name: Create a cluster using manifest file
      ansible.builtin.command:
        cmd: /usr/local/bin/kind create cluster --config {{ config_file_path }}
      when: multi_node

    - name: Add kubectl repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      
    - name: Kubectl install
      ansible.builtin.yum:
        name: kubectl
        state: present
...