- name: Enable docker repo
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Docker install
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Grant admin permissions to user on docker
  ansible.builtin.user:
    name: '{{ docker_user }}'
    groups: docker
    append: true
  when:  config_user
