---
- name: Habilita o repositório da Hashicorp
  ansible.builtin.yum_repository:
    name: hashicorp-repo
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Instala o vagrant
  ansible.builtin.yum:
    name: vagrant
    state: present
...
