multi_node: true
# a cluster with 2 workers and 1 control-plane
simple_three_node_cluster:
  - role: control-plane
  - role: worker
  - role: worker
# a cluster with 2 control-planes and 1 worker
ha_three_node_cluster:
  - role: control-plane
  - role: control-plane
  - role: worker